### ISSUE TITLE
remove comments when loading functions

### ISSUE THREAD

**Issue by SteveJustin1963** [orgMINT/MINT#18]
Change request - dump comments on upload from pc terminal as in ignore this `// comments.......`

When uploading a MINT code from pc terminal all comments after the `;` are copied to memory

But in asm80 termnal

> :A 1 2 +. // add;
> ^L
:A 1 2 +. // add;

but when
> :A 1 2 +. ; // add;
> ^L
:A 1 2 +. ;  //comments are gone

**Comment by jhlagado** [comment]
This is not valid MINT
```
:A 1 2 +. // add;
```
Don't put comments anywhere other than  after the last character of MINT code on the line
