### ISSUE TITLE
Incorrect terminology for array - change to vector

### ISSUE THREAD

**Issue by SteveJustin1963** [orgMINT/MINT#35]
Incorrect terminalology for `array` - change to `vector`

A vector as a list that has one dimension. 
` [1 2 3 4 5] a! !  // It is a row of data. 

An array is a list that is arranged in multiple dimensions. A two-dimensional array is a vector of vectors that are all of the same length, but width can vary. 

We dont have this feature in MINT but would look like this https://github.com/SteveJustin1963/MINTX.

**Comment by jhlagado** [comment]
Fair enough but this usage is common in computer languages (C, JavaScript etc)
Vector is a name sometimes used but in MINT and those other languages, arrays only have a single dimension and multidimensional arrays are built up from nested arrays
I am however in favour of a move toward more powerful arrays, this would be a major change to the language and not for the current v2 of MINT
