### ISSUE TITLE
variables and functions - extend by one character 

### ISSUE THREAD

**Issue by SteveJustin1963** [orgMINT/MINT#44]
my programs have exceeded single letters for variables and functions
need to extend by one character 
a-z add aa-zz
A-Z add AA-ZZ
26(single-letter)+676(two-letter)=702

**Comment by jhlagado** [comment]
This would quickly consume available memory. Each variable is two bytes. 
A-Z consumes 52 bytes, 
a-z consumes 52 bytes 
(total 104 bytes used in variables)

aa-zz would consume 1352 byes
AA-ZZ would consume 1352 byes
(total 2704 bytes used in variables)

Is this the best way to use memory?

I agree that there aren't enough variables in MINT but you could _try_ using arrays for additional variables
```
[ 0 0 0 0 0 ] a !
100 a 0 ? !
200 a 1 ? !
a 0 ? a 1 ? + a 2 ? !
a 2 ? .
```
```
300
```
